### ISSUE TITLE
methods test case error

### ISSUE THREAD

**Issue by ianstormtaylor** [component/props#2]
shouldn't the methods test case actually evaluate from:

```
file.type + " " + classes().join(" ")
```

to:

```
file classes
```

instead of:

```
file
```

that way if you have a template like this:

``` html
<h1>{name()}</h1>
```

the `name` prop will be subscribed to

**Comment by tj** [comment]
nope, we're just looking for props to subscribe to, the methods could be any arbitrary name, so unfortunately we have to define which props are used for those methods so rework still knows what to do. That would only work if the method names matched the property names, they might sometimes but yea

**Comment by ianstormtaylor** [comment]
ah good point. also just realized that with the other pull, this shouldnt matter. since method getter-setters should be transparent (as props) anyways
